### ISSUE TITLE
ParticleHydrodynamics2Controller is missing

### ISSUE THREAD

**Issue by BlizzCrafter** [UnterrainerInformatik/Metaballs#1]
The **ParticleHydrodynamics2Controller** used in your demo seems to be lost. Therfore I can't build the solution.

I also couldn't find it in the official Aether.Physics2D repo in the controllers section (https://github.com/tainicom/Aether.Physics2D/tree/master/Physics2D/Controllers).

Could you please help me finding this controller? Or is it still a work in progress?

Thank you for your time and help. Very nice project btw!

**Comment by BlizzCrafter** [comment]
Sorry I looked at the wrong branch. It's located in the SPH branch (https://github.com/tainicom/Aether.Physics2D/tree/SPH/Physics2D/Controllers). I used the NuGet of Aether.Physics2D that's why the controller was missing.

**Comment by BlizzCrafter** [comment]
Closed

**Comment by guFalcon** [comment]
Lol. Np.
Don't expect too much. I didn't get it to run with the library yet.
The SPH implementation still seems like a prototype to me...
And we expect our second baby-boy to arrive within the next three weeks... Everyone is expecting me to finish ThrobaxTD so that I can spend more time with my family... everything is very tense at the moment... not sure when I get to it.
